# when using the default proxy server port
local_backend: true

backend:
  name: git-gateway
media_folder: public/decap-assets/images
public_folder: "/decap-assets/images"
editor:
  preview: false
collections:
  - name: "landing-pages"
    label: "Landing Pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/content/landing-pages/home.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
  - name: "collection-item"
    label: "CollectionItem"
    folder: src/content/collection-items
    create: true
    fields:
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          pattern: ['^(\/).*', "Must start with '/'"],
        }
      - label: "Hero Image"
        name: "heroImage"
        widget: "object"
        fields:
          - { label: "src", name: "src", widget: "image" }
          - { label: "alt", name: "alt", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "content", widget: "markdown" }
  - name: "site-settings"
    label: "Site Settings"
    files:
      - label: "Main Menu"
        name: "main-menu"
        file: "src/content/site-settings/main-menu.md"
        fields:
          - label: "Nav Items"
            name: "navItems"
            widget: list
            types:
              - label: "Link"
                name: "link"
                widget: object
                summary: "{{fields.title}}"
                fields:
                  - { label: "Title", name: "title" }
                  - { label: "Relative URL", name: "relativeUrl" }
              - label: "Dropdown"
                name: "dropdown"
                widget: list
                summary: "{{fields.title}}"
                fields:
                  - { label: "Title", name: "title" }
                  - label: "Links"
                    name: "links"
                    widget: list
                    fields:
                      - { label: "Title", name: "title" }
                      - { label: "Relative URL", name: "relativeUrl" }
      - label: "Announcement Banner"
        name: "announcement-banner"
        file: "src/content/site-settings/announcement-banner.md"
        fields:
          - { label: "Enabled", name: "enabled", widget: boolean }
          - { label: "Text", name: "text", widget: string }
